name: Azure Static Web Apps & Function App CI/CD

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - dev
      - main

jobs:
  build_and_deploy_static_web_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_MUD_026AC8403 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/react-app"  # Adjust the path if your app is located elsewhere
          api_location: "/funcApp"    # Path to your Azure Function App code
          output_location: ""         # Adjust based on your static app output
          environment: ${{ github.ref == 'refs/heads/dev' && 'staging' || 'production' }}  # Use 'staging' for dev and 'production' for main

  build_and_deploy_function_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: ${{ github.ref == 'refs/heads/dev' && 'myFunctionApp1337' || 'myFunctionApp1337-prod' }}
          package: '.'   # This assumes your Azure Function App code is in the root; change if needed